models:
  - name: silver_teams
    description: "Cleared teams data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null

  - name: silver_players
    description: "Cleaned players data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: team
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')

  - name: silver_events
    description: "Cleaned events data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
  
  - name: silver_top_players
    description: "Top players, top transferred players etc. per gameweek."
    columns:
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: most_selected
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: most_transferred_in
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: top_element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: most_captained
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: most_vice_captained
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_fixtures
    description: "Cleaned fixtures data containing only main game stats."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: team_a
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')
      - name: team_h
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')

  - name: silver_chips_played
    description: "Top players, top transferred players etc. per gameweek."
    columns:
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')

  - name: silver_goalscorers_away
    description: "Goalscorers from away team per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_goalscorers_home
    description: "Goalscorers from home team per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_assistants_away
    description: "Assistants from away team per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_assistants_home
    description: "Assistants from home team per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_owngoalscorers_away
    description: "Own goalscorers from away team per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_owngoalscorers_home
    description: "Own goalscorers from home team per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_penalty_save_away
    description: "Penalty savers from away team per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_penalty_save_home
    description: "Penalty savers from home team per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_penalty_missed_away
    description: "Players from away team who missed penalty per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_penalty_missed_home
    description: "Players from home team who missed penalty per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_yellow_cards_away
    description: "Players from away team who saw yellow card per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_yellow_cards_home
    description: "Players from home team who saw yellow card per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_red_cards_away
    description: "Players from away team who saw red card per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_red_cards_home
    description: "Players from home team who saw red card per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_saves_away
    description: "Number of saves per player from away per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_saves_home
    description: "Number of saves per player from home per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_bonus_away
    description: "Players from away team who obtained bonus points per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_bonus_home
    description: "Players from home team who obtained bonus points per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_bps_away
    description: "Players from away team bps per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_bps_home
    description: "Players from home team bps per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_dc_away
    description: "Players from away team defensive contributions per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_dc_home
    description: "Players from home team defensive contributions per fixture"
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_players_history
    description: "Cleaned players history data."
    columns:
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: round
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: opponent_team
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')

  - name: silver_points_explain
    description: "Cleaned and indexed points explain data."
    columns:
      - name: id
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')

  - name: silver_teams_future_fixtures
    description: "Data on 5 next opponents for each team."
    columns:
      - name: id
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: opponent
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')