models:
  - name: silver_teams
    description: "Cleared teams data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null

  - name: silver_players
    description: "Cleaned players data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: team
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')

  - name: silver_events
    description: "Cleaned events data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
  
  - name: silver_top_players
    description: "Top players, top transferred players etc. per gameweek."
    columns:
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: most_selected
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: most_transferred_in
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: top_element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: most_captained
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: most_vice_captained
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')

  - name: silver_fixtures
    description: "Cleaned fixtures data containing only main game stats."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: team_a
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')
      - name: team_h
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')

  - name: silver_chips_played
    description: "Top players, top transferred players etc. per gameweek."
    columns:
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')

  - name: silver_players_history
    description: "Cleaned players history data."
    columns:
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: round
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: opponent_team
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')

  - name: silver_points_explain
    description: "Cleaned and indexed points explain data."
    columns:
      - name: id
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')

  - name: silver_teams_future_fixtures
    description: "Data on 5 next opponents for each team."
    columns:
      - name: id
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: opponent
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')

  - name: silver_fixtures_stats
    description: "Detailed stats per fixture and player."
    columns:
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_fixtures')
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_events')
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_players')
      - name: team
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('silver_teams')