snapshots:
  - name: elements_snapshot
    relation: source('raw', 'elements')
    config:
      schema: snapshots
      strategy: timestamp
      unique_key: id
      updated_at: ingestion_time
      hard_deletes: new_record