{{ config(
    alias='players'
)}}

select
    p.id as "ID",
    p.first_name as "First Name",
    p.second_name as "Second Name",
    p.chance_of_playing_next_round,
    p.chance_of_playing_this_round,
    p.code,
    p.cost_change_event,
    p.cost_change_event_fall,
    p.cost_change_start,
    p.cost_change_start_fall,
    p.dreamteam_count,
    case when p.element_type = 1 then 'Goalkeeper'
         when p.element_type = 2 then 'Defender'
         when p.element_type = 3 then 'Midfielder'
         when p.element_type = 4 then 'Forward'
         else 'Unknown' end as "Position",
    p.ep_next,
    p.ep_this,
    p.event_points,
    p.form,
    p.in_dreamteam,
    p.news,
    p.news_added,
    round(cast(p.now_cost as numeric)/10, 2) as "Price",
    p.points_per_game as "Points Per Game",
    p.selected_by_percent,
    p.status,
    t.name as "Team",
    p.total_points as "Points",
    p.transfers_in,
    p.transfers_in_event,
    p.transfers_out,
    p.transfers_out_event,
    p.value_form,
    p.value_season,
    p.web_name,
    p.region,
    p.team_join_date,
    p.birth_date,
    p.opta_code,
    p.minutes as "Minutes",
    p.goals_scored as "Goals",
    p.assists as "Assists",
    p.clean_sheets as "Clean Sheets",
    p.own_goals as "Own Goals",
    p.penalties_saved,
    p.penalties_missed,
    p.yellow_cards as "Yellow Cards",
    p.red_cards as "Red Cards",
    p.saves as "Saves",
    p.bonus as "Bonus",
    p.bps,
    p.influence,
    p.creativity,
    p.threat,
    p.ict_index,
    p.clearances_blocks_interceptions,
    p.recoveries,
    p.tackles,
    p.defensive_contribution as "Defensive Contribution",
    p.starts,
    p.expected_goals as "xG", 
    p.expected_assists as "xA",
    p.expected_goal_involvements as "xGI",
    p.expected_goals_conceded as "xGC",
    p.influence_rank,
    p.influence_rank_type,
    p.threat_rank,
    p.threat_rank_type,
    p.ict_index_rank_Type,
    p.corners_and_indirect_freekicks_order,
    p.direct_freekicks_order,
    p.penalties_order,
    p.expected_goals_per_90 as "xG90",
    p.saves_per_90 as "Saves90",
    p.expected_assists_per_90 as "xA90",
    p.expected_goal_involvements_per_90 as "xGI90",
    p.expected_goals_conceded_per_90 as "xGC90",
    p.goals_conceded_per_90 as "GC90",
    p.now_cost_rank,
    p.now_cost_rank_type,
    p.form_rank,
    p.form_rank_type,
    p.points_per_game_rank_type,
    p.selected_rank,
    p.selected_rank_type,
    p.starts_per_90,
    p.clean_sheets_per_90 as "CS90",
    p.defensive_contribution_per_90 as "DC90"
from {{ ref('silver_players') }} p
join {{ ref('silver_teams') }} t on t.id = team
order by p.id asc