CREATE TABLE IF NOT EXISTS raw.events (
	id int4,
	name text,
	deadline_time timestamp,
	release_time timestamp,
	average_entry_score int4,
	finished bool,
	data_checked bool,
	highest_scoring_entry int4,
	deadline_time_epoch int8,
	deadline_time_game_offset int4,
	highest_score int4,
	is_previous bool,
	is_current bool,
	is_next bool,
	cup_leagues_created bool,
	h2h_ko_matches_created bool,
	can_enter bool,
	can_manage bool,
	released bool,
	ranked_count int4,
	overrides jsonb,
	chip_plays jsonb,
	most_selected int4,
	most_transferred_in int4,
	top_element int4,
	top_element_info jsonb,
	transfers_made int4,
	most_captained int4,
	most_vice_captained int4,
	data_hash text,
	ingestion_time timestamp,
	PRIMARY KEY (id)
);