CREATE TABLE IF NOT EXISTS raw.fixtures (
	id int4,
	code int8,
	"event" int4,
	finished bool,
	finished_provisional bool,
	kickoff_time timestamp,
	minutes int4,
	provisional_start_time bool,
	started bool,
	team_a int4,
	team_a_score int4,
	team_h int4,
	team_h_score int4,
	stats jsonb,
	team_h_difficulty int4,
	team_a_difficulty int4,
	pulse_id int8,
	data_hash text,
	ingestion_time timestamp,
	PRIMARY KEY (id)
);