CREATE TABLE IF NOT EXISTS raw.teams (
	id int4 NULL,
	code int4 NULL,
	draw int4 NULL,
	form text NULL,
	loss int4 NULL,
	"name" text NULL,
	played int4 NULL,
	points int4 NULL,
	"position" int4 NULL,
	short_name text NULL,
	strength int4 NULL,
	team_division text NULL,
	unavailable bool NULL,
	win int4 NULL,
	strength_overall_home int4 NULL,
	strength_overall_away int4 NULL,
	strength_attack_home int4 NULL,
	strength_attack_away int4 NULL,
	strength_defence_home int4 NULL,
	strength_defence_away int4 NULL,
	pulse_id int4 NULL,
	data_hash text NULL,
	ingestion_time timestamp NULL,
	PRIMARY KEY (id)
);