models:
  - name: bronze_teams
    description: "Latest raw teams data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null

  - name: bronze_elements
    description: "Latest raw players data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: team
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_teams')

  - name: bronze_events
    description: "Latest raw events data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: most_selected
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_elements')
      - name: most_transferred_in
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_elements')
      - name: top_element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_elements')
      - name: most_captained
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_elements')
      - name: most_vice_captained
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_elements')
  
  - name: bronze_fixtures
    description: "Latest fixtures data."
    columns:
      - name: id
        data_tests:
          - unique
          - not_null
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_events')
      - name: team_a
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_teams')
      - name: team_h
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_teams')

  - name: bronze_players_history
    description: "Latests players history data."
    columns:
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_elements')
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_fixtures')
      - name: opponent_team
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_teams')
      - name: round
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_events')

  - name: bronze_players_fixtures
    description: "Latests players fixtures data."
    columns:
      - name: element
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_elements')
      - name: id
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_fixtures')
      - name: team_h
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_teams')
      - name: team_a
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_teams')
      - name: event
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_events')

  - name: bronze_points_explain
    description: "Latests points explain data."
    columns:
      - name: id
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_elements')
      - name: fixture
        data_tests:
          - relationships:
              arguments:
                field: id
                to: ref('bronze_fixtures')