MAIN_API = 'https://fantasy.premierleague.com/api/bootstrap-static/'
PLAYER_API = 'https://fantasy.premierleague.com/api/element-summary/'
MANAGER_API = 'https://fantasy.premierleague.com/api/entry/'
FIXTURES_API = 'https://fantasy.premierleague.com/api/fixtures/'
PERFORMANCE_GW_API = 'https://fantasy.premierleague.com/api/event/'
LOGS_FOLDER_NAME = 'logs/'
DBHANDLER_LOGS_FOLDER_NAME = 'dbhandler/'
